


#define ADC_BATTERY_VOLTAGE    ADC1_CHANNEL_4 // GPIO5

#define ADC_GENERATOR_CURRENT  ADC1_CHANNEL_6 // GPIO7

#define ADC_BATTERY_CURRENT    ADC1_CHANNEL_8 // GPIO9

#define LEDC_LS_CH0_GPIO       (21)
#define LEDC_LS_CH0_CHANNEL    LEDC_CHANNEL_0
#define LEDC_LS_CH0_SEL        (1ULL<<LEDC_LS_CH0_GPIO)

#define GPIO_SENS_PWR_EN       (33)
#define GPIO_SENS_PWR_EN_SEL   (1ULL<<GPIO_SENS_PWR_EN)

#define GPIO_LEVEL_1           (40)
#define GPIO_LEVEL_1_SEL       (1ULL<<GPIO_LEVEL_1)

#define GPIO_LEVEL_2           (41)
#define GPIO_LEVEL_2_SEL       (1ULL<<GPIO_LEVEL_2)

#define GPIO_POWER_OFF         (42)
#define GPIO_POWER_OFF_EN_SEL  (1ULL<<GPIO_POWER_OFF)


#define ALL_UNUSED_SEL         (0xFFFFFFFFFFFFFFFFULL & ~( 1ULL << 5 | 1ULL << 7 | 1ULL << 9 | LEDC_LS_CH0_SEL | GPIO_SENS_PWR_EN_SEL | GPIO_LEVEL_1_SEL | GPIO_LEVEL_2_SEL | GPIO_POWER_OFF_EN_SEL ))
